import { useEffect, useMemo, useState } from 'react'
import {
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  AreaChart,
  Area,
  LineChart,
  Line,
  ScatterChart,
  Scatter,
  ZAxis,
} from 'recharts'
import { Rich } from '../utils/text.jsx'
import ChatDock from '../components/ChatDock.jsx'
import AgentChart from '../components/AgentChart.jsx'
import HeroCanvas from '../components/HeroCanvas.jsx'

const DASHBOARD_KEY = 'media_measurement'
const BASE_TABS = ['Overview', 'Sentiment Analysis', 'Themes & Topics', 'Media Coverage', 'Key Stories']
const DYNAMIC_TAB = 'Dynamic Charts'

// Per-tab hero copy (fallback when the LLM storyboard chapter isn't available).
// `lead` is the white part of the headline, `em` the italic pink accent.
const TAB_HERO = {
  Overview: { label: 'The period at a glance', lead: 'The period,', em: 'measured end to end.', sub: 'Coverage volume, reach and sentiment across every tracked source.' },
  'Sentiment Analysis': { label: 'How sentiment moved', lead: 'The mood of the coverage,', em: 'day by day.', sub: 'Positive, neutral and negative split across the period.' },
  'Themes & Topics': { label: 'What drove the conversation', lead: 'The themes', em: 'that led the agenda.', sub: 'Which topics carried the volume — and how they were received.' },
  'Media Coverage': { label: 'Who carried the message', lead: 'The outlets and authors', em: 'behind the volume.', sub: 'Publications, reach and the bylines shaping the story.' },
  'Key Stories': { label: 'The stories that mattered', lead: 'The standout coverage,', em: 'good and bad.', sub: 'The most significant positive, neutral and negative articles.' },
  [DYNAMIC_TAB]: { label: 'On demand', lead: 'Charts,', em: 'built on request.', sub: 'Generated by the data agent from your questions.' },
}

// Split a storyboard title into a lead sentence + an italic accent remainder, e.g.
// "Research led the agenda. Regulatory close behind." → lead + em.
function splitHeadline(title) {
  if (!title) return { lead: '', em: '' }
  const m = String(title).match(/^(.*?[.!?])\s+(.+)$/)
  return m ? { lead: m[1], em: m[2] } : { lead: title, em: '' }
}

const SENT = {
  POS: { label: 'Positive', color: '#10b981' },
  NEG: { label: 'Negative', color: '#ef4444' },
  NEU: { label: 'Neutral', color: '#94a3b8' },
}
const PALETTE = ['#6366f1', '#8b5cf6', '#ec4899', '#f59e0b', '#10b981', '#3b82f6', '#14b8a6', '#f43f5e', '#a855f7', '#0ea5e9']

function nf(n) {
  if (n == null || Number.isNaN(n)) return '—'
  return new Intl.NumberFormat('en-US').format(n)
}
function compact(n) {
  if (n == null || Number.isNaN(n)) return '—'
  return new Intl.NumberFormat('en-US', { notation: 'compact', maximumFractionDigits: 1 }).format(n)
}
const MONTH_ABBR = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

// Format the date's own YYYY-MM-DD part — never via `new Date()`, which parses
// day keys as UTC midnight and can shift the day in the viewer's timezone.
function fmtDate(d) {
  if (!d) return ''
  const m = String(d).match(/^(\d{4})-(\d{2})-(\d{2})/)
  if (!m) return String(d)
  return `${MONTH_ABBR[Number(m[2]) - 1] || m[2]} ${Number(m[3])}`
}

// Respect the OS "reduce motion" setting — chart entrance animations are
// decorative, so we disable them when the user asks for less motion.
function usePrefersReducedMotion() {
  const [reduced, setReduced] = useState(
    () => typeof window !== 'undefined' && window.matchMedia?.('(prefers-reduced-motion: reduce)').matches,
  )
  useEffect(() => {
    const mq = window.matchMedia?.('(prefers-reduced-motion: reduce)')
    if (!mq) return undefined
    const onChange = (e) => setReduced(e.matches)
    mq.addEventListener?.('change', onChange)
    return () => mq.removeEventListener?.('change', onChange)
  }, [])
  return reduced
}

// A single themed tooltip so every chart matches the app surface/border/text in
// both light and dark mode (Recharts' default white tooltip is illegible on dark).
function ChartTip({ active, payload, label }) {
  if (!active || !payload?.length) return null
  const showLabel = label != null && label !== ''
  return (
    <div className="ctip">
      {showLabel && <div className="ctip__label">{fmtDate(label) || label}</div>}
      {payload.map((p, i) => (
        <div className="ctip__row" key={i}>
          <span className="ctip__swatch" style={{ background: p.color || p.fill || p.stroke }} />
          <span className="ctip__name">{p.name}</span>
          <span className="ctip__val">{nf(p.value)}</span>
        </div>
      ))}
    </div>
  )
}

// --- shells ----------------------------------------------------------------

// Two-line insight strip shown below every (non-KPI) chart.
function Insight({ text }) {
  if (!text) return null
  return (
    <p className="chartcard__insight">
      <Rich text={text} />
    </p>
  )
}

function ChartCard({ title, subtitle, insight, wide, children }) {
  return (
    <div className={`chartcard${wide ? ' chartcard--wide' : ''}`}>
      <div className="chartcard__head">
        <h3 className="chartcard__title">{title}</h3>
        {subtitle && <p className="chartcard__sub">{subtitle}</p>}
      </div>
      <div className="chartcard__body">{children}</div>
      <Insight text={insight} />
    </div>
  )
}

// Peak / lowest day chips + any LLM per-date insights, for time-series charts.
function DateInsights({ series, valueKey = 'count', dateInsights = [] }) {
  const stats = useMemo(() => {
    if (!Array.isArray(series) || series.length === 0) return null
    let hi = series[0]
    let lo = series[0]
    let sum = 0
    for (const d of series) {
      const v = Number(d[valueKey]) || 0
      sum += v
      if (v > (Number(hi[valueKey]) || 0)) hi = d
      if (v < (Number(lo[valueKey]) || 0)) lo = d
    }
    return { hi, lo, avg: sum / series.length }
  }, [series, valueKey])

  if (!stats && (!dateInsights || dateInsights.length === 0)) return null

  return (
    <div className="dateins">
      {stats && (
        <div className="dateins__chips">
          <span className="dateins__chip dateins__chip--hi">
            ▲ Peak · {fmtDate(stats.hi.date)} · {nf(stats.hi[valueKey])}
          </span>
          <span className="dateins__chip dateins__chip--lo">
            ▼ Lowest · {fmtDate(stats.lo.date)} · {nf(stats.lo[valueKey])}
          </span>
          <span className="dateins__chip">~ Avg · {stats.avg.toFixed(1)} / day</span>
        </div>
      )}
      {dateInsights?.map((di, i) => (
        <div className="dateins__card" key={i}>
          <div className="dateins__cardhead">
            <span className="dateins__date">{fmtDate(di.date)}</span>
            {di.pattern_type && <span className="dateins__tag">{di.pattern_type}</span>}
          </div>
          <p className="dateins__summary"><Rich text={di.summary} /></p>
          <div className="dateins__meta">
            {di.peak_day && <span>Peak: {di.peak_day}</span>}
            {di.avg && <span>Avg: {di.avg}</span>}
          </div>
        </div>
      ))}
    </div>
  )
}

// --- individual chart renderers --------------------------------------------

function SentimentDonut({ data }) {
  const reduced = usePrefersReducedMotion()
  const rows = ['POS', 'NEG', 'NEU']
    .map((k) => ({ key: k, name: SENT[k].label, value: data?.[k]?.count || 0, color: SENT[k].color }))
    .filter((r) => r.value > 0)
  if (!rows.length) return <Empty />
  return (
    <div className="donutwrap">
      <ResponsiveContainer width="100%" height={240}>
        <PieChart>
          <Pie data={rows} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={2} isAnimationActive={!reduced}>
            {rows.map((r) => (
              <Cell key={r.key} fill={r.color} />
            ))}
          </Pie>
          <Tooltip content={<ChartTip />} />
          <Legend />
        </PieChart>
      </ResponsiveContainer>
      <div className="donutwrap__center">
        <span className="donutwrap__num">{data?.net_sentiment_score ?? 0}</span>
        <span className="donutwrap__lbl">Net sentiment</span>
      </div>
    </div>
  )
}

function SentimentOverTime({ datewise }) {
  const reduced = usePrefersReducedMotion()
  const rows = useMemo(() => {
    if (!datewise || typeof datewise !== 'object') return []
    return Object.entries(datewise)
      .map(([date, v]) => ({ date, POS: v.POS || 0, NEG: v.NEG || 0, NEU: v.NEU || 0 }))
      .sort((a, b) => a.date.localeCompare(b.date))
  }, [datewise])
  if (!rows.length) return <Empty />
  return (
    <ResponsiveContainer width="100%" height={280}>
      <AreaChart data={rows} margin={{ top: 8, right: 12, left: -8, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
        <XAxis dataKey="date" tickFormatter={fmtDate} fontSize={11} />
        <YAxis fontSize={11} allowDecimals={false} />
        <Tooltip content={<ChartTip />} />
        <Legend />
        {['POS', 'NEU', 'NEG'].map((k) => (
          <Area key={k} type="monotone" dataKey={k} stackId="1" stroke={SENT[k].color} fill={SENT[k].color} fillOpacity={0.55} name={SENT[k].label} isAnimationActive={!reduced} />
        ))}
      </AreaChart>
    </ResponsiveContainer>
  )
}

function CoverageLine({ data }) {
  const reduced = usePrefersReducedMotion()
  if (!Array.isArray(data) || !data.length) return <Empty />
  return (
    <ResponsiveContainer width="100%" height={280}>
      <LineChart data={data} margin={{ top: 8, right: 12, left: -8, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
        <XAxis dataKey="date" tickFormatter={fmtDate} fontSize={11} />
        <YAxis fontSize={11} allowDecimals={false} />
        <Tooltip content={<ChartTip />} />
        <Line type="monotone" dataKey="count" stroke="#6366f1" strokeWidth={2.4} dot={{ r: 2 }} name="Articles" isAnimationActive={!reduced} />
      </LineChart>
    </ResponsiveContainer>
  )
}

function OriginalDonut({ data }) {
  const reduced = usePrefersReducedMotion()
  const rows = [
    { name: 'Original', value: data?.original?.count || 0, color: '#6366f1' },
    { name: 'Syndicated', value: data?.syndicated?.count || 0, color: '#f59e0b' },
  ].filter((r) => r.value > 0)
  if (!rows.length) return <Empty />
  return (
    <ResponsiveContainer width="100%" height={240}>
      <PieChart>
        <Pie data={rows} dataKey="value" nameKey="name" innerRadius={50} outerRadius={90} paddingAngle={2} isAnimationActive={!reduced}>
          {rows.map((r) => (
            <Cell key={r.name} fill={r.color} />
          ))}
        </Pie>
        <Tooltip content={<ChartTip />} />
        <Legend />
      </PieChart>
    </ResponsiveContainer>
  )
}

function ThemeBar({ data }) {
  const reduced = usePrefersReducedMotion()
  const rows = (Array.isArray(data) ? data : []).map((d) => ({
    theme: d.theme,
    POS: d.sentiments?.POS || 0,
    NEG: d.sentiments?.NEG || 0,
    NEU: d.sentiments?.NEU || 0,
    count: d.count,
  }))
  if (!rows.length) return <Empty />
  return (
    <ResponsiveContainer width="100%" height={Math.max(280, rows.length * 38)}>
      <BarChart layout="vertical" data={rows} margin={{ top: 8, right: 16, left: 8, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
        <XAxis type="number" fontSize={11} allowDecimals={false} />
        <YAxis type="category" dataKey="theme" width={140} fontSize={11} />
        <Tooltip content={<ChartTip />} cursor={{ fill: 'var(--surface-2)' }} />
        <Legend />
        {['POS', 'NEU', 'NEG'].map((k) => (
          <Bar key={k} dataKey={k} stackId="s" fill={SENT[k].color} name={SENT[k].label} isAnimationActive={!reduced} />
        ))}
      </BarChart>
    </ResponsiveContainer>
  )
}

function TopPublicationsBar({ data }) {
  const reduced = usePrefersReducedMotion()
  const rows = Array.isArray(data) ? data : []
  if (!rows.length) return <Empty />
  return (
    <ResponsiveContainer width="100%" height={Math.max(280, rows.length * 34)}>
      <BarChart layout="vertical" data={rows} margin={{ top: 8, right: 16, left: 8, bottom: 0 }}>
        <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
        <XAxis type="number" fontSize={11} allowDecimals={false} />
        <YAxis type="category" dataKey="label" width={160} fontSize={11} />
        <Tooltip content={<ChartTip />} cursor={{ fill: 'var(--surface-2)' }} />
        <Bar dataKey="count" name="Articles" radius={[0, 6, 6, 0]} isAnimationActive={!reduced}>
          {rows.map((_, i) => (
            <Cell key={i} fill={PALETTE[i % PALETTE.length]} />
          ))}
        </Bar>
      </BarChart>
    </ResponsiveContainer>
  )
}

function ReachSentimentScatter({ data }) {
  const reduced = usePrefersReducedMotion()
  const rows = (Array.isArray(data) ? data : []).map((d) => ({
    x: d.total_reach,
    y: d.net_sentiment,
    z: d.total_count,
    label: d.label,
  }))
  if (!rows.length) return <Empty />
  return (
    <ResponsiveContainer width="100%" height={300}>
      <ScatterChart margin={{ top: 12, right: 16, left: 0, bottom: 8 }}>
        <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
        <XAxis type="number" dataKey="x" name="Reach" tickFormatter={compact} fontSize={11} />
        <YAxis type="number" dataKey="y" name="Net sentiment" fontSize={11} />
        <ZAxis type="number" dataKey="z" range={[60, 600]} name="Articles" />
        <Tooltip
          cursor={{ strokeDasharray: '3 3' }}
          formatter={(v, n) => (n === 'Reach' ? compact(v) : v)}
          content={({ payload }) => {
            const p = payload?.[0]?.payload
            if (!p) return null
            return (
              <div className="rtip">
                <strong>{p.label}</strong>
                <div>Reach: {compact(p.x)}</div>
                <div>Net sentiment: {p.y}</div>
                <div>Articles: {p.z}</div>
              </div>
            )
          }}
        />
        <Scatter data={rows} fill="#6366f1" fillOpacity={0.7} isAnimationActive={!reduced} />
      </ScatterChart>
    </ResponsiveContainer>
  )
}

function Heatmap({ data }) {
  const rows = Array.isArray(data) ? data : []
  const max = useMemo(() => {
    let m = 0
    rows.forEach((r) => r.data?.forEach((c) => { if (c.count > m) m = c.count }))
    return m || 1
  }, [rows])
  if (!rows.length) return <Empty />
  return (
    <div className="heatmap">
      <div className="heatmap__row heatmap__row--head">
        <span className="heatmap__day" />
        {Array.from({ length: 24 }).map((_, h) => (
          <span key={h} className="heatmap__hcell">{h % 6 === 0 ? `${h}h` : ''}</span>
        ))}
      </div>
      {rows.map((r) => (
        <div className="heatmap__row" key={r.day}>
          <span className="heatmap__day">{r.day.slice(0, 3)}</span>
          {r.data.map((c) => (
            <span
              key={c.hour}
              className="heatmap__cell"
              title={`${r.day} ${c.hour}:00 · ${c.count} article${c.count === 1 ? '' : 's'}`}
              style={{ background: c.count ? `rgba(99,102,241,${0.15 + 0.85 * (c.count / max)})` : 'var(--surface-2)' }}
            />
          ))}
        </div>
      ))}
      {/* Scale legend — the color intensity alone isn't decodable without it. */}
      <div className="heatmap__legend">
        <span className="heatmap__legtxt">Less</span>
        {[0.15, 0.4, 0.65, 0.9].map((o) => (
          <span key={o} className="heatmap__legcell" style={{ background: `rgba(99,102,241,${o})` }} />
        ))}
        <span className="heatmap__legtxt">More · up to {nf(max)}/hr</span>
      </div>
    </div>
  )
}

function AuthorsTable({ data }) {
  const rows = Array.isArray(data) ? data : []
  if (!rows.length) return <Empty />
  return (
    <div className="mmtable__scroll">
      <table className="mmtable">
        <thead>
          <tr><th>Author</th><th>Publication</th><th>Theme</th><th>Articles</th><th>Sentiment</th></tr>
        </thead>
        <tbody>
          {rows.map((a, i) => (
            <tr key={i}>
              <td>{a.author || '—'}</td>
              <td>{a.publication || '—'}</td>
              <td>{a.theme || '—'}</td>
              <td>{nf(a.total_count)}</td>
              <td>
                {a.sentiment ? (
                  <span className="pill2" style={{ background: `${SENT[a.sentiment]?.color}22`, color: SENT[a.sentiment]?.color }}>
                    {SENT[a.sentiment]?.label || a.sentiment}
                  </span>
                ) : '—'}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function TopArticles({ data }) {
  const cols = ['POS', 'NEU', 'NEG']
  const has = cols.some((k) => (data?.[k] || []).length)
  if (!has) return <Empty />
  return (
    <div className="storiesgrid">
      {cols.map((k) => (
        <div className="storiescol" key={k}>
          <h4 className="storiescol__head" style={{ color: SENT[k].color }}>{SENT[k].label}</h4>
          {(data?.[k] || []).map((a, i) => (
            <article className="storycard" key={a.id ?? i}>
              <p className="storycard__title">{a.title}</p>
              <p className="storycard__meta">
                {a.domain || 'Unknown'} · {fmtDate(a.date)}{a.theme ? ` · ${a.theme}` : ''}
              </p>
              <p className="storycard__snippet">{a.content}</p>
            </article>
          ))}
          {(data?.[k] || []).length === 0 && <p className="muted">No articles.</p>}
        </div>
      ))}
    </div>
  )
}

function Empty() {
  return <div className="chartempty">No data for this chart.</div>
}

function Kpi({ label, value }) {
  return (
    <div className="kpi">
      <span className="kpi__value">{value}</span>
      <span className="kpi__label">{label}</span>
    </div>
  )
}

// Storyboard chapter shown at the top of a tab.
function Storyboard({ chapter }) {
  if (!chapter || (!chapter.title && !chapter.description)) return null
  return (
    <section className="story">
      {chapter.section_label && <p className="story__kicker">{chapter.section_label}</p>}
      {chapter.title && <h2 className="story__title">{chapter.title}</h2>}
      {chapter.description && <p className="story__desc">{chapter.description}</p>}
      {chapter.what_to_watch_for?.length > 0 && (
        <ul className="story__watch">
          {chapter.what_to_watch_for.map((w, i) => (
            <li key={i}>{w}</li>
          ))}
        </ul>
      )}
    </section>
  )
}

// --- main screen -----------------------------------------------------------

export default function MediaMeasurementScreen({ project, session, chartsData, chartsLoading = false, chartsError = '', onBack, onBackToReview }) {
  const [tab, setTab] = useState('Overview')
  // Charts the data agent produces while the user is on this dashboard.
  const [dynamicCharts, setDynamicCharts] = useState([])
  const TABS = dynamicCharts.length ? [...BASE_TABS, DYNAMIC_TAB] : BASE_TABS

  function handleAgentCharts(charts) {
    setDynamicCharts((prev) => [...charts, ...prev])
    setTab(DYNAMIC_TAB)
  }

  const byId = useMemo(() => {
    const arr = chartsData?.[DASHBOARD_KEY]
    const out = {}
    if (Array.isArray(arr)) arr.forEach((c) => { if (c?.chart_id) out[c.chart_id] = c })
    return out
  }, [chartsData])

  const insights = chartsData?.chart_insights || {}
  const overall = chartsData?.[`${DASHBOARD_KEY}_overall_summary`] || ''
  const chapters = chartsData?.storyboards?.[DASHBOARD_KEY] || []
  const chapterFor = (name) => chapters.find((c) => c.tab_name?.toLowerCase() === name.toLowerCase())

  const ins = (id) => insights[id]?.insight || ''
  const dateIns = (id) => insights[id]?.date_insights || []

  const sentiment = byId.sentiment_distribution
  const coverage = byId.datewise_coverage
  const theme = byId.theme_distribution
  const syndication = byId.original_vs_syndicated
  const totalCount = byId.total_count?.data?.total_count
  const totalReach = byId.total_reach?.data?.total_reach

  // Positive share, for the data-driven Overview headline.
  const posPct = (() => {
    const s = sentiment?.data
    const pos = s?.POS?.count || 0
    const denom = totalCount || (s?.POS?.count || 0) + (s?.NEG?.count || 0) + (s?.NEU?.count || 0)
    return denom ? Math.round((pos / denom) * 100) : 0
  })()

  // Hero copy changes per tab — prefer the LLM storyboard chapter, else a static
  // fallback. The Overview tab always shows the data-driven "{N} articles. {x}% ran
  // positive." headline.
  const heroFor = (name) => {
    if (name === 'Overview') {
      const ch = chapterFor('Overview')
      return {
        kicker: `Media Measurement · ${ch?.section_label || TAB_HERO.Overview.label}`,
        lead: `${nf(totalCount)} articles.`,
        em: `${posPct}% ran positive.`,
        sub: ch?.description || TAB_HERO.Overview.sub,
      }
    }
    const ch = chapterFor(name)
    if (ch && (ch.title || ch.description)) {
      const { lead, em } = splitHeadline(ch.title)
      return {
        kicker: `Media Measurement · ${ch.section_label || TAB_HERO[name]?.label || name}`,
        lead: lead || TAB_HERO[name]?.lead || name,
        em: em || TAB_HERO[name]?.em || '',
        sub: ch.description || TAB_HERO[name]?.sub || '',
      }
    }
    const f = TAB_HERO[name] || { label: name, lead: name, em: '', sub: '' }
    return { kicker: `Media Measurement · ${f.label}`, lead: f.lead, em: f.em, sub: f.sub }
  }
  const hero = heroFor(tab)

  if (chartsLoading) {
    // Skeleton screen (not a blocking spinner) so the layout is visible while
    // charts stream in — reduces perceived wait and avoids a layout jump.
    return (
      <div className="dashstack" aria-busy="true" aria-label="Loading dashboard">
        <div className="skel skel--hero" />
        <div className="kpirow">
          {[0, 1, 2].map((i) => <div key={i} className="skel skel--kpi" />)}
        </div>
        <div className="skel skel--card skel--wide" />
        <div className="chartgrid">
          {[0, 1].map((i) => <div key={i} className="skel skel--card" />)}
        </div>
        <span className="sronly">Loading dashboard…</span>
      </div>
    )
  }
  if (chartsError) {
    return (
      <div className="state state--error">
        <p>{chartsError}</p>
      </div>
    )
  }

  return (
    <>
      <div className="mmhero mmhero--weekly mmhero--bleed">
        <HeroCanvas palette="weekly" className="mmhero__canvas" />
        <div className="mmhero__grain" />
        <div className="mmhero__vignette" />
        <div className="mmhero__inner">
          {(onBack || onBackToReview) && (
            <div className="mmhero__backrow">
              {onBack && <button className="mmhero__back" onClick={onBack}>← Back to dashboards</button>}
              {onBackToReview && (
                <button className="mmhero__back" onClick={onBackToReview}>← Back to review</button>
              )}
            </div>
          )}
          <div className="mmhero__kicker"><span className="mmhero__dot" /> {hero.kicker}</div>
          <h1 className="mmhero__h1">{hero.lead} {hero.em && <em>{hero.em}</em>}</h1>
          {hero.sub && <p className="mmhero__sub">{hero.sub}</p>}
          <div className="mmhero__stats">
            <div className="mmhero__stat"><div className="mmhero__statn">{nf(totalCount)}</div><div className="mmhero__statl">Total articles</div></div>
            <div className="mmhero__stat"><div className="mmhero__statn">{compact(totalReach)}</div><div className="mmhero__statl">Total reach</div></div>
            <div className="mmhero__stat"><div className="mmhero__statn">{sentiment?.data?.net_sentiment_score ?? '—'}</div><div className="mmhero__statl">Net sentiment</div></div>
          </div>
        </div>
      </div>

      <div className="tabbar" role="tablist" aria-label="Dashboard sections">
        {TABS.map((t) => (
          <button
            key={t}
            className={`tabbtn${tab === t ? ' tabbtn--on' : ''}`}
            role="tab"
            aria-selected={tab === t}
            onClick={() => setTab(t)}
          >
            {t}
          </button>
        ))}
      </div>

      {/* ---------------- Overview ---------------- */}
      {tab === 'Overview' && (
        <div className="dashstack">
          {overall && (
            <section className="summary">
              <p className="summary__kicker">OVERALL SUMMARY</p>
              <p className="summary__body"><Rich text={overall} /></p>
            </section>
          )}

          <Storyboard chapter={chapterFor('Overview')} />

          <div className="kpirow">
            <Kpi label="Total Articles" value={nf(totalCount)} />
            <Kpi label="Total Reach" value={compact(totalReach)} />
            <Kpi label="Net Sentiment" value={sentiment?.data?.net_sentiment_score ?? '—'} />
          </div>

          {coverage && (
            <ChartCard title={coverage.title} subtitle={coverage.description} insight={ins('datewise_coverage')} wide>
              <CoverageLine data={coverage.data} />
              <DateInsights series={coverage.data} dateInsights={dateIns('datewise_coverage')} />
            </ChartCard>
          )}

          <div className="chartgrid">
            {sentiment && (
              <ChartCard title={sentiment.title} subtitle={sentiment.description} insight={ins('sentiment_distribution')}>
                <SentimentDonut data={sentiment.data} />
              </ChartCard>
            )}
            {theme && (
              <ChartCard title={theme.title} subtitle={theme.description} insight={ins('theme_distribution')}>
                <ThemeBar data={theme.data} />
              </ChartCard>
            )}
          </div>

          {syndication && (
            <ChartCard title={syndication.title} subtitle={syndication.description} insight={ins('original_vs_syndicated')}>
              <OriginalDonut data={syndication.data} />
            </ChartCard>
          )}
        </div>
      )}

      {/* ---------------- Sentiment Analysis ---------------- */}
      {tab === 'Sentiment Analysis' && (
        <div className="dashstack">
          <Storyboard chapter={chapterFor('Sentiment Analysis')} />
          {sentiment && (
            <>
              <div className="chartgrid">
                <ChartCard title={sentiment.title} subtitle={sentiment.description} insight={ins('sentiment_distribution')}>
                  <SentimentDonut data={sentiment.data} />
                </ChartCard>
              </div>
              <ChartCard title="Sentiment Over Time" subtitle="Daily positive / neutral / negative coverage split." insight={ins('sentiment_distribution')} wide>
                <SentimentOverTime datewise={sentiment.data?.datewise_distribution} />
                <DateInsights
                  series={Object.entries(sentiment.data?.datewise_distribution || {}).map(([date, v]) => ({
                    date,
                    count: (v.POS || 0) + (v.NEG || 0) + (v.NEU || 0),
                  }))}
                  dateInsights={dateIns('sentiment_distribution')}
                />
              </ChartCard>
            </>
          )}
        </div>
      )}

      {/* ---------------- Themes & Topics ---------------- */}
      {tab === 'Themes & Topics' && (
        <div className="dashstack">
          <Storyboard chapter={chapterFor('Themes & Topics')} />
          {theme && (
            <ChartCard title={theme.title} subtitle={theme.description} insight={ins('theme_distribution')} wide>
              <ThemeBar data={theme.data} />
            </ChartCard>
          )}
        </div>
      )}

      {/* ---------------- Media Coverage ---------------- */}
      {tab === 'Media Coverage' && (
        <div className="dashstack">
          <Storyboard chapter={chapterFor('Media Coverage')} />
          <div className="chartgrid">
            {byId.top_publications && (
              <ChartCard title={byId.top_publications.title} subtitle={byId.top_publications.description} insight={ins('top_publications')}>
                <TopPublicationsBar data={byId.top_publications.data} />
              </ChartCard>
            )}
            {byId.publication_reach_sentiment && (
              <ChartCard title={byId.publication_reach_sentiment.title} subtitle={byId.publication_reach_sentiment.description} insight={ins('publication_reach_sentiment')}>
                <ReachSentimentScatter data={byId.publication_reach_sentiment.data} />
              </ChartCard>
            )}
          </div>
          {byId.publish_time_heatmap && (
            <ChartCard title={byId.publish_time_heatmap.title} subtitle={byId.publish_time_heatmap.description} insight={ins('publish_time_heatmap')} wide>
              <Heatmap data={byId.publish_time_heatmap.data} />
            </ChartCard>
          )}
          {byId.top_authors_by_publications && (
            <ChartCard title={byId.top_authors_by_publications.title} subtitle={byId.top_authors_by_publications.description} insight={ins('top_authors_by_publications')} wide>
              <AuthorsTable data={byId.top_authors_by_publications.data} />
            </ChartCard>
          )}
        </div>
      )}

      {/* ---------------- Key Stories ---------------- */}
      {tab === 'Key Stories' && (
        <div className="dashstack">
          <Storyboard chapter={chapterFor('Key Stories')} />
          {byId.top_articles_by_sentiment && (
            <ChartCard title={byId.top_articles_by_sentiment.title} subtitle={byId.top_articles_by_sentiment.description} insight={ins('top_articles_by_sentiment')} wide>
              <TopArticles data={byId.top_articles_by_sentiment.data} />
            </ChartCard>
          )}
        </div>
      )}

      {/* ---------------- Dynamic Charts (agent-generated) ---------------- */}
      {tab === DYNAMIC_TAB && (
        <div className="dashstack">
          <section className="summary">
            <p className="summary__kicker">DYNAMIC CHARTS</p>
            <p className="summary__body">
              Charts generated on demand by the data agent. Ask for more from the chat in the bottom-right.
            </p>
          </section>
          {dynamicCharts.length === 0 ? (
            <div className="chartempty">No agent charts yet — ask the data agent to build one.</div>
          ) : (
            <div className="chartgrid">
              {dynamicCharts.map((c, i) => (
                <ChartCard key={`${c.chart_id}-${i}`} title={c.title || c.chart_id} subtitle={c.description}>
                  <AgentChart chart={c} />
                </ChartCard>
              ))}
            </div>
          )}
        </div>
      )}

      <ChatDock sessionId={session?.id} mode="route" onCharts={handleAgentCharts} />
    </>
  )
}
